### ISSUE TITLE
Main.py: AttributeError: 'NoneType' object has no attribute 'shape' with image

### ISSUE THREAD

**Issue by heoa** [SeuTao/Kaggle_Whale2019_2nd_palce_solution#3]
I got the main.py finally running but getting the error in its execution such that `$ python main.py` fires the errors below.

```
    (binary_head): BinaryHead(
      (fc): Sequential(
        (0): Linear(in_features=2048, out_features=10008, bias=True)
      )
    )
  )
)
change lr: 0.0001
change hard_ratio: 0.01
NW ratio!!!!!!! : 0.25
NW id num!!!!!! : 8
66656
Traceback (most recent call last):
  File "main.py", line 486, in <module>
    main(config)
  File "main.py", line 450, in main
    run_train(config)
  File "main.py", line 239, in run_train
    for input, truth_ , truth_NW_binary in train_loader:
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hhh/Kaggle/Humpback-Whale-Identification-Challenge-2019_2nd_palce_solution/process/data.py", line 88, in __getitem__
    image = get_cropped_img(image, self.bbox_dict[os.path.split(image_path)[1]], is_mask=False)
  File "/home/hhh/Kaggle/Humpback-Whale-Identification-Challenge-2019_2nd_palce_solution/process/augmentation.py", line 113, in get_cropped_img
    size_x = image.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

```

**Comment by heoa** [comment]
Mission solved, had to remove preceding forward slash such that


```
$ head process/data_helper.py 
from include import *
import pandas as pd
from process.augmentation import *

PJ_DIR = r''#r'/Kaggle_Whale2019_2nd_place_solution'#project path
train_df = pd.read_csv('train.csv') #train.csv path
TRN_IMGS_DIR = 'train/'#train data path
TST_IMGS_DIR = 'test/'
#LIST_DIR = PJ_DIR + r'/image_list'
LIST_DIR = PJ_DIR + r'image_list/'

```
