### ISSUE TITLE
Main.py: CUDA out of memory, ability builtin to free memory?

### ISSUE THREAD

**Issue by heoa** [SeuTao/Kaggle_Whale2019_2nd_palce_solution#4]
Is there some way already builtin to free memory in `main.py`? I have tried the following `torch.cuda.empty_cache()`, added it here-and-there in `main.py`, to free memory but still getting the memory error.

```
change lr: 0.0001
change hard_ratio: 0.01
NW ratio!!!!!!! : 0.25
NW id num!!!!!! : 8
66656
Traceback (most recent call last):
  File "main.py", line 486, in <module>
    main(config)
  File "main.py", line 450, in main
    run_train(config)
  File "main.py", line 256, in run_train
    logit, logit_softmax, feas = net.forward(input, label = truth_, is_infer = True)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hhh/Kaggle/Humpback-Whale-Identification-Challenge-2019_2nd_palce_solution/net/model_resnet101.py", line 80, in forward
    x = self.basemodel.layer3(x)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py", line 87, in forward
    out = self.conv3(out)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hhh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.89 GiB total capacity; 14.89 GiB already allocated; 197.50 MiB free; 992.00 KiB cached)
```

**Comment by usuyama** [comment]
@heoa I faced the same issue with P40 (24GB VRAM). It started working after reducing the batch size (args in main.py) to 64 from 128.
